### ISSUE TITLE
error of LOHHLA

### ISSUE THREAD

**Issue by lizhenli8888** [slagtermaarten/LOHHLA#2]
Dear authors, when running LOHHLA,  the following error ocurrs to some of the samples. 
I do not understand the warning of "Run with coverageStep  completed first".
My code and the warning are pasted bellow, and how can I  do to get the correct result.

Rscript /root/lohhla/LOHHLAscript.R   --patientId 1218-1  --outputDir /data/1218-1/lohhla-normal/  \
--normalBAMfile /data/1218-1/1218-2_BS_GL.bam \
--BAMDir /data/1218-1/ \
--hlaPath /data/hla_format/1218-2.hla_format \
--HLAfastaLoc  /root/lohhla/data/abc_complete.fasta \
--CopyNumLoc /data/purity/1218-1.purity \
--mappingStep TRUE --minCoverageFilter 10 --fishingStep TRUE --cleanUp FALSE  \
--HLAexonLoc  /root/lohhla/data/hla.dat \
--gatkDir /picard --novoDir /novocraft \
--coverageStep  TRUE

Warning messages:
1: Run with coverageStep completed first -- skipping 1218-1-hla_a! 
2: Run with coverageStep completed first -- skipping 1218-1-hla_b! 
3: Run with coverageStep completed first -- skipping 1218-1-hla_c! 
Error in is.data.frame(x) : object 'combinedTable' not found
Calls: write.table -> is.data.frame
Execution halted

Thank you very much!

**Comment by slagtermaarten** [comment]
This might not necessarily solve your problem but it will likely solve others; I noticed you did not include the --tumorBAMfile flag. If I remember correctly, that one is essential. Could you try and rerun with this flag and report back?
Best, Maarten

**Comment by lizhenli8888** [comment]
Dear author:

Thank you for your reply.
I used the Rscript from https://bitbucket.org/mcgranahanlab/lohhla/src/master/ last time, which did not define the tumor bam file, but expect the tumor and normal bam  in the same folder.
I also tired the Rscript from github,  the new problem occured.  the code and he error message are as follows:


Rscript /data/LOHHLA/LOHHLAscript.R   --patientId 1218-1  --outputDir /data/1218-1/lohhla-normal3/  \
--normalBAMfile /data/1218-1/1218-2_BS_GL.bam \
--tumorBAMfile /data/1218-1/1218-1.bam \
--BAMDir /data/1218-1/ \
--hlaPath /data/hla_format/1218-2.hla_format \
--HLAfastaLoc  /root/lohhla/data/abc_complete.fasta \
--CopyNumLoc /data/purity/1218-1.purity \
--mappingStep TRUE --minCoverageFilter 10 --fishingStep TRUE --cleanUp FALSE  \
--HLAexonLoc  /root/lohhla/data/hla.dat \
--gatkDir /picard --novoDir /novocraft \
--LOHHLA_loc /data/LOHHLA/ \
--genomeAssembly hg19 \
--coverageStep  TRUE



[mpileup] 1 samples in 1 input files
<mpileup> Set max per-file depth to 8000
Fri Aug 16 10:21:43 2019 - hla_c_03_02_02_01	258	G	0		

Fri Aug 16 10:21:43 2019 - samtools mpileup /data/1218-1/lohhla-normal3/1218-2_BS_GL/1218-2_BS_GL.type.hla_c_07_02_01_01.filtered.bam -f /root/lohhla/data/abc_complete.fasta > /data/1218-1/lohhla-normal3/1218-2_BS_GL.hla_c_07_02_01_01.normal.mpileup

[mpileup] 1 samples in 1 input files
<mpileup> Set max per-file depth to 8000
Fri Aug 16 10:21:43 2019 - hla_c_07_02_01_01	207	A	1	^g.	A

Error: object 'forceRedo' not found
Execution halted




And I also tried one sample which could successfully run and get the HLAlossPrediction_CI.xls using the R scirpt from https://bitbucket.org/mcgranahanlab/lohhla/src/master/, but it returned the same error of "Error: object 'forceRedo' not found" while using the github version of Rscript.



Thank you!

**Comment by slagtermaarten** [comment]
Thanks for using my fork and sorry for my late reply, your message hadn't caught my attention (will try to be more vigilant in the future!). While re-running LOHHLA, I also noticed this bug and fixed it. Please see the new commit. Cheers, M

**Comment by emiliamoralest** [comment]
Hello @lizhenli8888, I have encountered the same problem as you "Run with coverageStep completed first -- skipping 1218-1-hla_a!", were you able to solve it? Thanks!
