### ISSUE TITLE
Discrepancy with example run

### ISSUE THREAD

**Issue by fsvarn** [slagtermaarten/LOHHLA#3]
When running this modified script on the example file, I am getting discrepancies in the 'PVal_unique' and 'UnPairedPval_unique' from the solution in the `example-file/correct-example-out/example.10.DNA.HLAlossPrediction_CI.xls` file. Specifically, the p-values from the modified run are 0.32 and 0.72, respectively, while the original run has p-values of 8e-26 and 1.5e-28. Notably, the 'PVal' and 'UnPairedPval' columns appear similar (but not identical), as do the other columns.

Have the authors encountered a similar issue? I've attached the list of conda packages I have loaded when running LOHHLA and my output.

Thanks!

[conda_packages_lohhla.txt](https://github.com/slagtermaarten/LOHHLA/files/4156643/conda_packages_lohhla.txt)

[example.10.DNA.HLAlossPrediction_CI.20200204.txt](https://github.com/slagtermaarten/LOHHLA/files/4156739/example.10.DNA.HLAlossPrediction_CI.20200204.txt)

**Comment by slagtermaarten** [comment]
I hadn't tried running the example with my version of LOHHLA, conveniently assuming the functionality would remain identical. I can confirm that the results are slightly different from the example output (first row is original, second one my run):

```
                 region       HLA_A_type1       HLA_A_type2
1: example_tumor_sorted hla_a_01_01_01_01 hla_a_24_02_01_01
2:                 <NA> hla_a_01_01_01_01 hla_a_24_02_01_01
   HLAtype1Log2MedianCoverage HLAtype2Log2MedianCoverage
1:                   0.625692                      -1.72
2:                   0.000167                      -2.04
   HLAtype1Log2MedianCoverageAtSites HLAtype2Log2MedianCoverageAtSites
1:                          0.668616                             -2.05
2:                          0.000167                             -2.12
   HLA_type1copyNum_withoutBAF HLA_type1copyNum_withoutBAF_lower
1:                        1.58                             1.503
2:                        0.90                             0.886
   HLA_type1copyNum_withoutBAF_upper HLA_type1copyNum_withBAF
1:                             1.650                     1.57
2:                             0.965                     1.65
   HLA_type1copyNum_withBAF_lower HLA_type1copyNum_withBAF_upper
1:                           1.48                           1.62
2:                           1.62                           1.74
   HLA_type2copyNum_withoutBAF HLA_type2copyNum_withoutBAF_lower
1:                      0.0271                            0.0196
2:                      0.0145                           -0.0170
   HLA_type2copyNum_withoutBAF_upper HLA_type2copyNum_withBAF
1:                            0.0883                   0.0383
2:                            0.0230                   0.1860
   HLA_type2copyNum_withBAF_lower HLA_type2copyNum_withBAF_upper
1:                         0.0216                         0.0912
2:                         0.1392                         0.2026
   HLA_type1copyNum_withoutBAFBin HLA_type1copyNum_withoutBAFBin_lower
1:                           1.53                                 1.34
2:                           1.67                                 1.52
   HLA_type1copyNum_withoutBAFBin_upper HLA_type1copyNum_withBAFBin
1:                                 1.62                        1.44
2:                                 1.76                        1.65
   HLA_type1copyNum_withBAFBin_lower HLA_type1copyNum_withBAFBin_upper
1:                              1.33                              1.63
2:                              1.55                              1.78
   HLA_type2copyNum_withoutBAFBin HLA_type2copyNum_withoutBAFBin_lower
1:                         0.0576                               0.0409
2:                         1.6683                               1.5226
   HLA_type2copyNum_withoutBAFBin_upper HLA_type2copyNum_withBAFBin
1:                                0.164                       0.122
2:                                1.762                       0.211
   HLA_type2copyNum_withBAFBin_lower HLA_type2copyNum_withBAFBin_upper     PVal
1:                            0.0189                             0.179 8.87e-48
2:                            0.1279                             0.265 6.04e-51
   UnPairedPval PVal_unique UnPairedPval_unique        LossAllele
1:     9.18e-54    8.75e-26            1.58e-28 hla_a_24_02_01_01
2:     1.19e-56    3.20e-01            7.21e-01 hla_a_24_02_01_01
          KeptAllele numMisMatchSitesCov propSupportiveSites            message
1: hla_a_01_01_01_01                  92                 100               <NA>
2: hla_a_01_01_01_01                  92                 100 analysis_completed
```

At the moment I have no ideas as to what could be causing these differences, hopefully will have time to look into this in the next few days.

**Comment by slagtermaarten** [comment]
And sorry for the late reply! I hadn't noticed the github notification email until just now...

**Comment by slagtermaarten** [comment]
Hi, I have resolved this, please see the latest commit. Cheers, M

**Comment by giovianco** [comment]
Good day,

I'm running the latest commit but still find the same numbers in PVal_unique and UnPairedPval_unique columns.

[example.10.DNA.HLAlossPrediction_CI.20210826.csv](https://github.com/slagtermaarten/LOHHLA/files/7059356/example.10.DNA.HLAlossPrediction_CI.20210826.csv)

Also, some plots are missing from the Figures file:

[example_tumor_sorted.minCoverage_10.HLA.pdf](https://github.com/slagtermaarten/LOHHLA/files/7059363/example_tumor_sorted.minCoverage_10.HLA.pdf)

Any suggestion?

Thank you very much for this fork!

**Comment by slagtermaarten** [comment]
Hi, thanks for your message. I haven't focused at all on getting the plots to work again. I won't have time to delve into the p-value issue anytime soon. I myself have only used the PVal_unique values in my follow up analyses, I don't think I saw a need for the unpairedpval_unique values. If you're willing to fix any issues you encounter, I'd be happy to merge them in (and give you credit for it somehow)
