### ISSUE TITLE
suggestions for the script

### ISSUE THREAD

**Issue by xhy1219** [slagtermaarten/LOHHLA#4]
Hi! Thanks for your fork provides the option for hg38! But I think there are some bugs in your latest script. 

For line 627 and 628, I think they should be removed, otherwise, the command --plottingStep can not be used if the output directory does not exist.

if (plottingStep)
    stopifnot(dir.exists(figureDir))

Also, in the plotting parts, some parameters' names are not completed which leads the incomplete of the figure result. (All the plot which xlab = 'HLA genomic position')
For example:
plot(c(1:max(HLA_A_type1normal$V2, HLA_A_type2normal$V2))
                     , lim = c(0, max(HLA_A_type1normalCov, HLA_A_type2normalCov)), col ='#3182bd99', pch = 16
                     , lab = 'HLA genomic position'
                     , lab = 'Coverage'
                     , ain = c(paste("HLA normal coverage", sample))
                     , ex = 0.75
                     , ype = 'n'
                     , as = 1)

**Comment by slagtermaarten** [comment]
Hi, I haven't paid much attention to the plotting part of the script, as I haven't been using it. If you could send me a pull request, I'd be happy to merge your fixes.

**Comment by yufang-web** [comment]
Hello when i run the plotting parts it shows that the NA occurs when the variable is changed. It seems that there are some issue with the variable or data frame used to draw the picture.  the problem probably due to  HLA_A_type2tumorCov.
maybe the charactor to numeric .i am not sure. 
 In plot.window(...) :

**Comment by BGI2016** [comment]
Hello，I would like to know how to determine the occurrence of LOH for an HLA allele from the output file. My value of HLA_type1copyNum_withBAFBin and HLA_type2copyNum_withBAFBin are negative.Is the output HLA_type1copyNum_withBAFBin and HLA_type2copyNum_withBAFBin the log2 value of the copy number？

**Comment by slagtermaarten** [comment]
> Hello，I would like to know how to determine the occurrence of LOH for an HLA allele from the output file. My value of HLA_type1copyNum_withBAFBin and HLA_type2copyNum_withBAFBin are negative.Is the output HLA_type1copyNum_withBAFBin and HLA_type2copyNum_withBAFBin the log2 value of the copy number？

Hi BGI, these should be mean estimates of integer allele copy numbers. I myself have used 'HLA_type{1,2}copyNum_withBAF' in my work (without the 'Bin'), but I don't quite recall why I thought those were superior at the moment. Also look at the associated confidence intervals ('_lower' and '_upper' appendixes), especially if your estimates deviate strongly from an integer or are lower than 0.

**Comment by MagicalLily** [comment]
> > 您好，我想知道如何从输出文件中确定 HLA 等位基因的 LOH 出现。我的HLA_type1copyNum_withBAFBin和HLA_type2copyNum_withBAFBin的值都是负数，输出的HLA_type1copyNum_withBAFBin和HLA_type2copyNum_withBAFBin是拷贝数的log2值吗？
> 
> 嗨 BGI，这些应该是整数等位基因拷贝数的平均估计值。我自己在我的工作中使用了 'HLA_type{1,2}copyNum_withBAF'（没有使用 'Bin'），但我不太记得为什么我现在认为这些更好。还要查看相关的置信区间（'_lower' 和 '_upper' 附录），尤其是当您的估计值严重偏离整数或低于 0 时。



> > Hello，I would like to know how to determine the occurrence of LOH for an HLA allele from the output file. My value of HLA_type1copyNum_withBAFBin and HLA_type2copyNum_withBAFBin are negative.Is the output HLA_type1copyNum_withBAFBin and HLA_type2copyNum_withBAFBin the log2 value of the copy number？
> 
> Hi BGI, these should be mean estimates of integer allele copy numbers. I myself have used 'HLA_type{1,2}copyNum_withBAF' in my work (without the 'Bin'), but I don't quite recall why I thought those were superior at the moment. Also look at the associated confidence intervals ('_lower' and '_upper' appendixes), especially if your estimates deviate strongly from an integer or are lower than 0.

Thank you very much for your reply. To determine HLA LOH calls,can we use the cutoffs specified in the
LOHHLA output file which ends '.HLAlossPrediction CI.xls': HLA_type1/2copyNum_withBAFBin or HLA_type1/2copyNum_withBAF is <0.5 and Pval_unique  is <0.01?

> > Hello，I would like to know how to determine the occurrence of LOH for an HLA allele from the output file. My value of HLA_type1copyNum_withBAFBin and HLA_type2copyNum_withBAFBin are negative.Is the output HLA_type1copyNum_withBAFBin and HLA_type2copyNum_withBAFBin the log2 value of the copy number？
> 
> Hi BGI, these should be mean estimates of integer allele copy numbers. I myself have used 'HLA_type{1,2}copyNum_withBAF' in my work (without the 'Bin'), but I don't quite recall why I thought those were superior at the moment. Also look at the associated confidence intervals ('_lower' and '_upper' appendixes), especially if your estimates deviate strongly from an integer or are lower than 0.

Thank you very much for your reply. To determine HLA LOH calls,can we use the cutoffs specified in the
LOHHLA output file which ends '.HLAlossPrediction CI.xls': HLA_type1/2copyNum_withBAFBin or HLA_type1/2copyNum_withBAF is <0.5 and Pval_unique  is <0.01?

**Comment by BGI2016** [comment]
> > Hello，I would like to know how to determine the occurrence of LOH for an HLA allele from the output file. My value of HLA_type1copyNum_withBAFBin and HLA_type2copyNum_withBAFBin are negative.Is the output HLA_type1copyNum_withBAFBin and HLA_type2copyNum_withBAFBin the log2 value of the copy number？
> 
> Hi BGI, these should be mean estimates of integer allele copy numbers. I myself have used 'HLA_type{1,2}copyNum_withBAF' in my work (without the 'Bin'), but I don't quite recall why I thought those were superior at the moment. Also look at the associated confidence intervals ('_lower' and '_upper' appendixes), especially if your estimates deviate strongly from an integer or are lower than 0.

Thank you very much for your reply. To determine HLA LOH calls,can we use the cutoffs specified in the
LOHHLA output file which ends '.HLAlossPrediction CI.xls': HLA_type1/2copyNum_withBAFBin or HLA_type1/2copyNum_withBAF is <0.5 and Pval_unique  is <0.01?

**Comment by slagtermaarten** [comment]
I would probably use either 'Bin' or not 'Bin' and not both but your approach seems valid and more sensitive at the potential cost of being less precise. Do check your calls for some samples with the raw data. I'm curious to hear about your results.

**Comment by BGI2016** [comment]
Thank you very much for your reply. The attachment is the result of six samples I ran.The value of HLA_type*copyNum_withBAFBin is either less than 0, greater than 1, or between 0 and 1.However, I am not sure if it is reasonable to consistently set the threshold for HLA_type*copyNum_withBAFBin to less than 0.5, especially when negative values occur. May I know if the HLA_type*copyNum_withBAFBin of the samples you analyzed is either less than 0 or greater than 1? What causes this and what suggestions do you have for setting the threshold? I need a clear threshold setting for the next analysis, thank you very much.

[Samples.DNA.HLAlossPrediction_CI.xls](https://github.com/slagtermaarten/LOHHLA/files/9887195/Samples.DNA.HLAlossPrediction_CI.xls)

**Comment by slagtermaarten** [comment]
I'm sorry, I have been away from LOHHLA for too long. Please ask the original authors for help.

I *can* imagine your purity values are off and that causes your estimates to assume weird values. Regarding thresholds, I don't recall the availability of clear guidelines, but again, I haven't checked the original paper and there might be some in there.

**Comment by slagtermaarten** [comment]
BTW, greater than 1 shouldn't be surprising. (Whole) genome duplications happen regularly in cancer and HLA alleles might very well be located on duplicated chromosomes. Less than 0 is not theoretically possible of course and indicates an issue. Perhaps you should ignore calls with less than X (50?) available supportive sites. You could plot supportive sites vs. allele count estimates to see whether all/most of the unexpected count estimates are with low numbers of supportive sites.
