### ISSUE TITLE
Issue of running LOHHLA with example data

### ISSUE THREAD

**Issue by QianhuiXu** [slagtermaarten/LOHHLA#5]
Hello,

LOHHLA is a wonderful tool！
I ran into an issue with running LOHHLA with example data.

My command:
Rscript LOHHLAscript.R \
	--LOHHLA_loc=/home/shpc_10066/lohhla/ \
	--patientId test \
	--outputDir /home/shpc_10066/lohhla/example-file/output \
	--normalBAMfile /home/shpc_10066/lohhla/example-file/bam/example_BS_GL_sorted.bam \
	--tumorBAMfile /home/shpc_10066/lohhla/example-file/bam/example_tumor_sorted.bam \
	--BAMDir /home/shpc_10066/lohhla/example-file/bam/ \
	--hlaPath /home/shpc_10066/lohhla/example-file/hlas \
	--HLAfastaLoc /home/shpc_10066/lohhla/abc_complete.fasta \
	--CopyNumLoc /home/shpc_10066/lohhla/example-file/solutions.txt \
	--mappingStep TRUE \
	--minCoverageFilter 10 \
	--fishingStep TRUE \
	--cleanUp TRUE \
	--gatkDir /home/shpc_10066/anaconda3/envs/lohhla/share/picard-2.5.0-2/ \
	--novoDir /home/shpc_10066/anaconda3/pkgs/novoalign-3.07.00-0/bin/
Output was listed in the record file.
[record.txt](https://github.com/slagtermaarten/LOHHLA/files/10049481/record.txt)

I'm really at a loss as to how to proceed, and any guidance would be much appreciated!
Thank you for your kind help!

**Comment by slagtermaarten** [comment]
Hi, please make sure the correct software versions are in your PATH. You're not getting any output tsv/xls? The log seems fine mostly.

**Comment by slagtermaarten** [comment]
Anyone reading this and wanting to resolve this, feel free to make a Docker image that includes exactly the right depedencies :)
