### ISSUE TITLE
Why is NA in copy number

### ISSUE THREAD

**Issue by xiasijian** [slagtermaarten/LOHHLA#6]
![image](https://user-images.githubusercontent.com/39158528/225566807-4b75a516-7148-4e2f-8ebb-807cdf159871.png)

Hi, thanks for your excellent software, why does it have NA in copy number?

**Comment by xiasijian** [comment]
![image](https://user-images.githubusercontent.com/39158528/225571519-af209395-a9e1-4d52-ae81-09537c01bde7.png)

**Comment by haoqing12** [comment]
I have the same problem may I ask how you solved it?
