### ISSUE TITLE
Pval_Unique is NA in some samples

### ISSUE THREAD

**Issue by zhangyz1997** [slagtermaarten/LOHHLA#7]
I ran LOHHLA on my data and got NA values for PVal_unique and UnPairedPval_unique column in the output file. I want to know why this happened and how I can fix it.
I have attached the log file and the output file for your reference. Could you please take a look and let me know what went wrong?

[Sample_P17005037LU01.10.DNA.HLAlossPrediction_CI.20230313.txt](https://github.com/slagtermaarten/LOHHLA/files/11273792/Sample_P17005037LU01.10.DNA.HLAlossPrediction_CI.20230313.txt)
[Sample_P17005037LU01.10.DNA.IntegerCPN_CI.20230313.txt](https://github.com/slagtermaarten/LOHHLA/files/11273793/Sample_P17005037LU01.10.DNA.IntegerCPN_CI.20230313.txt)
[running.hla.loh.exome@Mon_Mar_13_06-12-24_2023.log](https://github.com/slagtermaarten/LOHHLA/files/11273781/running.hla.loh.exome%40Mon_Mar_13_06-12-24_2023.log)

**Comment by slagtermaarten** [comment]
I haven't delved too deeply (I don't maintain this tool, it wasn't mine to begin with) but but I noticed insanely high copy number estimates in your data. Are your purity estimates (too) low?

**Comment by slagtermaarten** [comment]
I think not enough *unique* overlapping reads were available in this sample at the genomic loci of SNPs that LOHHLA uses to compare the two alleles of the HLA genes in question. Was the overall sequencing quality lower for the samples that 'failed' LOHHLA here?
